exclude: '^$'
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: forbid-binary
      - id: forbid-space-in-indent
      - id: git-check  # Configure in .gitattributes
      - id: git-dirty  # Configure in .gitignore
      - id: markdownlint # Configure in .mdlrc
      - id: shellcheck
      - id: shfmt