exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
      - id: shellcheck #need shellcheck: brew install shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
  # php linter, will need a local install to run the hooks
  # get it from https://github.com/squizlabs/PHP_CodeSniffer
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    sha: 1.3.0
    hooks:
      - id: php-lint
      - id: php-cs
        exclude: \.(blade)
        files: \.(php)$
        args: [--standard=PSR1 -p]
      - id: php-cs-fixer
        exclude: \.(blade)
        files: \.(php)$
        args: [--rules=@PSR1]