exclude: '^$'
fail_fast: false
repos:
  - repo: local # If your hooks are created locally
    hooks:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    sha: 1.11.0
    hooks:
      - id: git-check  # Configure in .gitattributes
      - id: git-dirty  # Configure in .gitignore
      - id: shellcheck
  - repo: git@github.com:hootsuite/pre-commit-php.git
    sha: 1.1.0
    hooks:
      - id: php-lint-all