version: "3"

services:
  php:
    image: markoshust/lumen-php-apache:7.2-0
    build: .
    volumes:
      - ~/.composer:/root/.composer:delegated
      - ./src:/var/www/html
    links:
      - db
      - cache
    ports:
      - 8081:80
  db:
    image: mysql:5.6
    volumes:
     - /Applications/MAMP/db/mysql56:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumen
      MYSQL_PASSWORD: secret
  cache:
    image: memcached
