version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/php:7.2-apache-browsers # ...with this image as the primary container; this is where all `steps` will run
        environment:
          APP_ENV: testing
          APP_DEBUG: true
          APP_KEY: kjcndjjksddwdwdw
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: webform
          DB_USERNAME: root
          DB_PASSWORD: 1234
          CACHE_DRIVER: file
          QUEUE_DRIVER: sync
      - image: circleci/mysql:5.6-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: '1234'
          MYSQL_DATABASE: webform
    working_directory: ~/project # directory where steps will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run: a2enmod rewrite
      - run: docker-php-ext-install mysqli pdo_mysql
      - run:
          name: Install Project Dependencies
          command: composer install -n --prefer-dist
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Update Missed Dependencies
          command: composer update
      - run: php artisan migrate:refresh --force
      - run: php artisan db:seed

      - run: ./vendor/bin/codecept run
      - run:
          name: Install nodejs which is needed by codeceptjs
          command: apt-get update -yq && apt-get install curl gnupg -yq && curl -sL https://deb.nodesource.com/setup_8.x | bash && apt-get install nodejs wget -yq
      - run:
          name: Install chromium which is needed by codeceptjs
          command: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && apt-get update && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends && rm -rf /var/lib/apt/lists/*
      - run:
          name: Install puppeteer
          command: cd tests/frontend | npm install codeceptjs puppeteer
      - run: cd tests/frontend | npx codeceptjs run
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
