version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/php:7.2-apache-browsers # ...with this image as the primary container; this is where all `steps` will run
        environment:
          APP_ENV: testing
          APP_DEBUG: true
          APP_KEY: kjcndjjksddwdwdw
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: webform
          DB_USERNAME: root
          DB_PASSWORD: 1234
          CACHE_DRIVER: file
          QUEUE_DRIVER: sync
      - image: circleci/mysql:5.6-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: '1234'
          MYSQL_DATABASE: webform
    working_directory: /home/circleci/project # directory where steps will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run: sudo a2enmod rewrite
      - run: sudo docker-php-ext-install mysqli pdo_mysql
      - run:
          name: Install Project Dependencies
          command: composer install -n --prefer-dist
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v2-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v2-
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v2-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Update Missed Dependencies
          command: composer update
      - run: php artisan migrate:refresh --force
      - run: php artisan db:seed
      - run: ./vendor/bin/codecept run
      - run:
          name: install node and npm
          command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | source ~/.bashrc | nvm install node
      - run:
          name: Install puppeteer
          command: cd tests/frontend | npm install codeceptjs puppeteer
      - run:
          name: Configure & start Apache
          command: sudo cp /home/circleci/project/docker/conf/000-default.conf /etc/apache2/sites-available/000-default.conf | sudo service apache2 start
      - run: cd tests/frontend | npx codeceptjs run
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
