version: "3"

services:
  php:
    image: markoshust/lumen-php-apache:7.2-0
    build: .
    volumes:
      - ~/.composer:/root/.composer:delegated
      - ./src:/var/www/html
      - ./conf/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./conf/ssl:/etc/apache2/ssl
    links:
      - db
    ports:
      - 8080:80
      - 443:443
  db:
    image: mysql:5.6
    volumes:
     - /Applications/MAMP/db/mysql56:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
