version: "3"

services:
  apache_php:
    image: markoshust/lumen-php-apache:7.2-0
    build: .
    volumes:
      - ~/.composer:/root/.composer:delegated
      - ../:/var/www/html
      - ./conf/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./conf/ssl:/etc/apache2/ssl
    links:
      - db
    ports:
      - 80:80
      - 443:443
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
     - ./mysql-data:/docker-entrypoint-initdb.d
    ports:
     - 3307:3307
